export const DEFAULT_TABLE_PREFIX = "LANGGRAPH_";
export const ORACLE_IDENTIFIER_MAX_LENGTH = 128;
export const STORE_NAMESPACE_PATH_MAX_BYTES = 4000;
export const STORE_KEY_MAX_BYTES = 1024;
export const STORE_FIELD_PATH_MAX_BYTES = 1024;
export const JSON_VALUE_VARCHAR_MAX_BYTES = 4000;
export const VECTOR_STRING_BIND_MAX_BYTES = 32767;
export const STORE_KEY_ENCODING_PREFIX = "b64:";
